# Generated by Django 6.0.3 on 2026-05-01 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('describetion', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.FloatField(null=True)),
                ('off_price', models.FloatField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('review', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=200, null=True)),
                ('rate', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('confirm', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoplist.itemlist')),
            ],
            options={
                'verbose_name': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_box', models.BooleanField(default=False)),
                ('item_bought', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoplist.itemlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trades',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('post', models.BooleanField(default=False)),
                ('delievered', models.BooleanField(default=False)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoplist.trade')),
            ],
        ),
    ]
